# Generated by Django 5.1 on 2024-08-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="recipe name", max_length=255)),
                ("ingredients", models.TextField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("posted_date", models.DateField()),
            ],
        ),
    ]
