# Generated by Django 5.1 on 2024-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recipeapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="recipes/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(default="name", max_length=255),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="posted_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
